### ISSUE TITLE
couldn't find file 'font_awesome5' with type 'text/css'

### ISSUE THREAD

**Issue by toepokesoftware** [tomkra/font_awesome5_rails#6]
I'm getting the following error using version 0.2.4.

My pages render correctly.  The error only occurs in my tests.

```
Error:
Admin::SearchesControllerTest#test_0003_#index - filter by ip_province:
ActionView::Template::Error: couldn't find file 'font_awesome5' with type 'text/css'
Checked in these paths: 
  /Users/henry/mrkey/development/mrkey/app/assets/config
  /Users/henry/mrkey/development/mrkey/app/assets/images
  /Users/henry/mrkey/development/mrkey/app/assets/javascripts
  /Users/henry/mrkey/development/mrkey/app/assets/stylesheets
  /Users/henry/mrkey/development/mrkey/lib/assets/billing
  /Users/henry/mrkey/development/mrkey/lib/assets/import
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/mrkey-selectize-1.3.0/app/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/jquery-ui-rails-6.0.1/app/assets/images
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/jquery-ui-rails-6.0.1/app/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/jquery-ui-rails-6.0.1/app/assets/stylesheets
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/font-awesome-rails-4.7.0.3/app/assets/fonts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/font-awesome-rails-4.7.0.3/app/assets/stylesheets
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/cloudinary-1.8.2/vendor/assets/html
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/cloudinary-1.8.2/vendor/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/chartkick-2.2.5/app/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/chartkick-2.2.5/vendor/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/actioncable-5.1.4/lib/assets/compiled
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/assets/compiled
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/turbolinks-source-5.1.0/lib/assets/javascripts
  /Users/henry/mrkey/development/mrkey/node_modules
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/popper_js-1.12.9/assets/javascripts
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/bootstrap-4.0.0/assets/stylesheets
  /Users/henry/.rvm/gems/ruby-2.4.1/gems/bootstrap-4.0.0/assets/javascripts
    app/assets/stylesheets/application.scss:16
    app/views/layouts/admin.html.erb:7:in `_app_views_layouts_admin_html_erb__2129801279448301864_70212484526020'
    app/controllers/application_controller.rb:36:in `render'
    test/controllers/admin/searches_controller_test.rb:23:in `block in <class:SearchesControllerTest>'
```

Any suggestions?

**Comment by tomkra** [comment]
Hello, I've updated gem and did some changes to assets try to upgrade to latest version. If problem still persist can you provide failing test? Thank you.
