### ISSUE TITLE
 cannot load such file -- sassc

### ISSUE THREAD

**Issue by MarchandMD** [tomkra/font_awesome5_rails#73]
- rails 7 app
- installed gem with `bundle add font_awesome5_rails`
- ran `bundle install`
- ran `bundle`
- added `*= require font_awesome5_webfont` to `application.css`
- restarted server
- added `<%= fa_icon "fa_guitar" %>` to `.html.erb` view
- navigated to page and received the following error: 

<img width="1042" alt="Screen Shot 2023-10-28 at 9 09 14 PM" src="https://github.com/tomkra/font_awesome5_rails/assets/35391349/b1c7ac88-3e6c-4eb5-8c2f-ea61ade1ccb5">

stack trace: 

```
bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
zeitwerk (2.6.12) lib/zeitwerk/kernel.rb:38:in `require'
sprockets (4.2.1) lib/sprockets/autoload/sassc.rb:2:in `<main>'
bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bootsnap (1.16.0) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
zeitwerk (2.6.12) lib/zeitwerk/kernel.rb:38:in `require'
sprockets (4.2.1) lib/sprockets/sassc_processor.rb:42:in `initialize'
sprockets (4.2.1) lib/sprockets/sassc_processor.rb:27:in `new'
sprockets (4.2.1) lib/sprockets/sassc_processor.rb:27:in `instance'
sprockets (4.2.1) lib/sprockets/sassc_processor.rb:31:in `call'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:33:in `call'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets (4.2.1) lib/sprockets/loader.rb:184:in `load_from_unloaded'
sprockets (4.2.1) lib/sprockets/loader.rb:59:in `block in load'
sprockets (4.2.1) lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
sprockets (4.2.1) lib/sprockets/loader.rb:43:in `load'
sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `block in load'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `load'
sprockets (4.2.1) lib/sprockets/bundle.rb:41:in `block in call'
sprockets (4.2.1) lib/sprockets/utils.rb:175:in `dfs'
sprockets (4.2.1) lib/sprockets/bundle.rb:42:in `call' 
sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets (4.2.1) lib/sprockets/loader.rb:184:in `load_from_unloaded'
sprockets (4.2.1) lib/sprockets/loader.rb:59:in `block in load'
sprockets (4.2.1) lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
sprockets (4.2.1) lib/sprockets/loader.rb:43:in `load'
sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `block in load'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `load'
sprockets (4.2.1) lib/sprockets/bundle.rb:32:in `block in call'
/Users/michaelmarchand/.rbenv/versions/3.1.4/lib/ruby/3.1.0/set.rb:511:in `each_key'
/Users/michaelmarchand/.rbenv/versions/3.1.4/lib/ruby/3.1.0/set.rb:511:in `each'
sprockets (4.2.1) lib/sprockets/bundle.rb:31:in `call'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets (4.2.1) lib/sprockets/loader.rb:184:in `load_from_unloaded'
sprockets (4.2.1) lib/sprockets/loader.rb:59:in `block in load'
sprockets (4.2.1) lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
sprockets (4.2.1) lib/sprockets/loader.rb:43:in `load'
sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `block in load'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `load'
sprockets (4.2.1) lib/sprockets/base.rb:81:in `find_asset'
sprockets (4.2.1) lib/sprockets/base.rb:88:in `find_all_linked_assets'
sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `each'
sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `to_a'
sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize' 
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
concurrent-ruby (1.2.2) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker' 
```

FYSA: am using tailwindcss

**Comment by J-Verz** [comment]
Experiencing the same issue when I tried dropping sassc-rails as a dependency in my app. Some of the asset files in this gem are Sass, not CSS, and so a Sass preprocessor is needed. I'd say there are two solutions:

1. Explicitly add sassc-rails/sass-rails as a dependency in the gemspec
2. Convert the sass to CSS (I don't really see anything in those files that isn't possible in CSS) so no preprocessor is needed
